### ISSUE TITLE
Remove support for auto-extracting Active Model attributes?

### ISSUE THREAD

**Issue by kaspth** [bullet-train-co/jbuilder-schema#14]
If you pass an Active Model-like collection to Jbuilder, you have to pass what keys you want extract, i.e.:

```ruby
json.articles @articles, :id, :content
json.articles @articles # This won't work.
```

However, we've added a feature to automatically extract every attribute so the second code line works.

It doesn't sound right to me that we covertly add this feature. @newstler what do you think, or is there something I'm misunderstanding here?

**Comment by kaspth** [comment]
It's this line that does it by the way: https://github.com/bullet-train-co/jbuilder-schema/blob/65d3aeeb82f4787143fca813b22124f7a73becff/lib/jbuilder/schema/template.rb#L133

**Comment by newstler** [comment]
@kaspth Sorry, I've been out of computer due to moving to another country.

I've checked that, and cannot confirm: for me both options worked in Jbuilder:
```
json.articles @articles, :id, :content
json.articles @articles
```
But the second option didn't work in Jbuilder::Schema, it produced only empty `articles` field with a description.

**Comment by newstler** [comment]
I noticed that what you wrote is true for `extract!`:
```
json.extract! article, :id, :content # Works in Jbuilder and Jbuilder::Schema
json.extract! article # Doesn't produce anything in both Jbuilder and Jbuilder::Schema
```

**Comment by kaspth** [comment]
Hm, this is really odd to me. From looking at the Jbuilder source I don't see how this works, maybe it somehow calls `as_json`? I'll need to look into this more.

**Comment by newstler** [comment]
I also thought so, but it doesn't seem so, as I tried to change `as_json` and nothing happened.

**Comment by kaspth** [comment]
I just got back to this and double checked, and it looks like it's `as_json` that does the extraction work. This is me fiddling with stuff in the template test file:

```ruby
  Article.class_eval do
    def as_json(options = nil)
      { hello: :there }
    end
  end

  test "collections" do
    p Jbuilder.new { _1.articles Article.all }.target!
```

which outputs `"{\"articles\":[{\"hello\":\"there\"},{\"hello\":\"there\"},{\"hello\":\"there\"},{\"hello\":\"there\"},{\"hello\":\"there\"}]}"`

If I just try to print out the JSON attributes directly, the objects haven't had their attributes extracted yet:

```ruby
p Jbuilder.new { _1.articles Article.all.to_a }.attributes!
# => {"articles"=>[#<Article id: 1, user_id: 1, status: nil, title: "Generic title 0", body: "Lorem ipsum… 0", created_at: "2023-01-03 00:30:22.357048000 +0000", updated_at: "2023-01-03 00:30:22.357048000 +0000">, #<Article id: 2, user_id: 1, status: nil, title: "Generic title 1", body: "Lorem ipsum… 1", created_at: "2023-01-03 00:30:22.357411000 +0000", updated_at: "2023-01-03 00:30:22.357411000 +0000">, #<Article id: 3, user_id: 1, status: nil, title: "Generic title 2", body: "Lorem ipsum… 2", created_at: "2023-01-03 00:30:22.357740000 +0000", updated_at: "2023-01-03 00:30:22.357740000 +0000">, #<Article id: 4, user_id: 1, status: nil, title: "Generic title 3", body: "Lorem ipsum… 3", created_at: "2023-01-03 00:30:22.358025000 +0000", updated_at: "2023-01-03 00:30:22.358025000 +0000">, #<Article id: 5, user_id: 1, status: nil, title: "Generic title 4", body: "Lorem ipsum… 4", created_at: "2023-01-03 00:30:22.358298000 +0000", updated_at: "2023-01-03 00:30:22.358298000 +0000">]}
```

So it's gotta be `as_json` that does the extraction itself when no explicit arguments have been provided. I think we can close this now.
