### ISSUE TITLE
Update for Rails 7.1.0

### ISSUE THREAD

**Issue by newstler** [bullet-train-co/jbuilder-schema#54]
Some tests are failing.

**Comment by jagthedrummer** [comment]
I just dug into this a little bit. I don't fully understand what's going on, but I did find a clue.

It looks like the return value of this method changes from rails `7.0.x` to `7.1.0` but I'm not sure why.

https://github.com/bullet-train-co/jbuilder-schema/blob/f5ddafc4c810afce7704da0fb9c7047f09b74f85/lib/jbuilder/schema/renderer.rb#L21-L41

In `7.0.x` it returns a `Hash` but in `7.1.0` it returns a `String`.

**Comment by jagthedrummer** [comment]
The `String` in question looks like somewhere along the line we're calling `.to_s` on a `Hash`.

```
"{:type=>:object, :title=>\"Teams\", :description=>\"Teams\", :required=>[\"id\", \"name\"], :properties=>{\"id\"=>{:type=>:integer, :description=>\"Team ID\"}, \"name\"=>{:type=>:string, :description=>\"Team\"}, \"time_zone\"=>{:type=>[:string, \"null\"], :description=>\"Primary Time Zone\"}, \"locale\"=>{:type=>[:string, \"null\"], :description=>\"Language\"}, \"created_at\"=>{:type=>[:string, \"null\"], :format=>\"date-time\", :description=>\"Signed Up At\"}, \"updated_at\"=>{:type=>[:string, \"null\"], :format=>\"date-time\", :description=>\"Updated At\"}}, :example=>{\"id\"=>163, \"name\"=>\"EXAMPLE Generic Team 1\", \"time_zone\"=>\"International Date Line West\", \"locale\"=>\"en\", \"created_at\"=>\"2023-10-09T17:03:53.949Z\", \"updated_at\"=>\"2023-10-09T17:03:53.949Z\"}}
```

**Comment by jagthedrummer** [comment]
Just to document the error that we're seeing in the starter repo:

```
Error:
Api::OpenApiControllerTest#test_OpenAPI_document_is_valid:
ActionView::Template::Error: undefined method `deep_stringify_keys' for "{:type=>:object, :title=>\"Teams\", :description=>\"Teams\", :required=>[\"id\", \"name\"], :properties=>{\"id\"=>{:type=>:integer, :description=>\"Team ID\"}, \"name\"=>{:type=>:string, :description=>\"Team\"}, \"time_zone\"=>{:type=>[:string, \"null\"], :description=>\"Primary Time Zone\"}, \"locale\"=>{:type=>[:string, \"null\"], :description=>\"Language\"}, \"created_at\"=>{:type=>[:string, \"null\"], :format=>\"date-time\", :description=>\"Signed Up At\"}, \"updated_at\"=>{:type=>[:string, \"null\"], :format=>\"date-time\", :description=>\"Updated At\"}}, :example=>{\"id\"=>172, \"name\"=>\"EXAMPLE Generic Team 1\", \"time_zone\"=>\"International Date Line West\", \"locale\"=>\"en\", \"created_at\"=>\"2023-10-06T19:23:27.244+09:00\", \"updated_at\"=>\"2023-10-06T19:23:27.244+09:00\"}}":String
    core/bullet_train-api/app/helpers/api/open_api_helper.rb:62:in `automatic_components_for'
    app/views/api/v1/open_api/index.yaml.erb:18
    core/bullet_train-api/app/controllers/api/open_api_controller.rb:12:in `index'
    core/bullet_train/app/controllers/concerns/controllers/base.rb:95:in `set_locale'
    test/controllers/api/open_api_controller_test.rb:10:in `block in <class:OpenApiControllerTest>'
```

**Comment by kaspth** [comment]
Hey yeah, @newstler and I are looking into this too.

The line that changed in Rails is here https://github.com/rails/rails/blob/70c28cfcbfb83db31f53c86ed1eb8358e0b2ecb5/actionview/lib/action_view/template.rb#L254

Also looks like there was a incompatibility with regular jbuilder here https://github.com/rails/rails/pull/46298

And the `to_s` call was added here https://github.com/rails/rails/pull/45756

I'll look into a fix.

**Comment by kaspth** [comment]
Got a version over here that lets us skip `eval`, though it's hacky too https://github.com/bullet-train-co/jbuilder-schema/pull/57

**Comment by jagthedrummer** [comment]
👍 That's a lot better than my `eval` fix.

**Comment by kaspth** [comment]
@jagthedrummer good point in https://github.com/bullet-train-co/bullet_train/pull/1064 that we'd need a new release of jbuilder-schema to merge that Starter Repo PR.

@newstler can you release a new version? (I don't have owner rights on RubyGems).

**Comment by newstler** [comment]
@kaspth Thanks for figuring that out!
Just published v.2.4.0 with this update.

**Comment by jagthedrummer** [comment]
Excellent, thank you!
